### ISSUE TITLE
Add RSS feed?

### ISSUE THREAD

**Issue by Pat-Lafon** [azdavis/azdavis.net#9]
Hey, I came across your blog, specifically https://azdavis.net/posts/rust-2023/ from the most recent This Week in Rust. Have you considered adding an RSS feed that can be subscribed to? To be honest, I'm not sure what's involved except the ease of use on my end of just copying website links and entering them into NetNewsWire.

**Comment by azdavis** [comment]
There's one: https://azdavis.net/posts/feed.xml

**Comment by azdavis** [comment]
Thanks for reading (:

**Comment by azdavis** [comment]
I made it so the RSS link is included on every post, not just the page that lists all the posts.

**Comment by Pat-Lafon** [comment]
Works for me now, thanks!
